"""update planets table with sizes and distances

Revision ID: 4cf79676e61c
Revises: 67b470e66d7c
Create Date: 2025-01-07 10:08:53.308183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf79676e61c'
down_revision: Union[str, None] = '67b470e66d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('size', sa.Float(), nullable=False))
    op.add_column('planets', sa.Column('orbital_distance', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'orbital_distance')
    op.drop_column('planets', 'size')
    # ### end Alembic commands ###
